---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: influxdb
    image: influxdb
    privileged: True
    groups:
      - influxdb
  - name: telegraf-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - telegraf
  - name: telegraf-debian
    image: minimum2scp/systemd-stretch
    privileged: True
    command: /sbin/init
    groups:
      - telegraf
  - name: telegraf-ubuntu
    image: solita/ubuntu-systemd:bionic
    privileged: True
    command: /sbin/init
    groups:
      - telegraf

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        telegraf_plugins_default:
          - plugin: cpu
            config:
            - percpu = true
          - plugin: disk
          - plugin: io
          - plugin: mem
          - plugin: net
          - plugin: system
          - plugin: swap
          - plugin: netstat
          - plugin: processes
          - plugin: kernel
          - plugin: nginx
            config:
            - urls = ["http://localhost/nginx_status"]
          - plugin: logparser
            config:
              - files = ["/var/log/nginx/access.log"]
              - from_beginning = true
              - name_override = "nginx_access_log"
              - \[logparser.grok\]
              -   patterns = ["%{COMBINED_LOG_FORMAT}"]

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
